// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiGP.Data;

namespace WebApiGP.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220406100146_AddTableDatabase")]
    partial class AddTableDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiGP.Data.Admin", b =>
                {
                    b.Property<long>("idAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("idGiaPha")
                        .HasColumnType("bigint");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAdmin");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("WebApiGP.Data.AdminFamily", b =>
                {
                    b.Property<long>("idAdminFamily")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("idFamily")
                        .HasColumnType("bigint");

                    b.Property<long>("idGiaPha")
                        .HasColumnType("bigint");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAdminFamily");

                    b.ToTable("AdminFamily");
                });

            modelBuilder.Entity("WebApiGP.Data.ClientDetail", b =>
                {
                    b.Property<long>("idClientDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diedDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("idFamily")
                        .HasColumnType("bigint");

                    b.Property<long>("idGiaPhaChild")
                        .HasColumnType("bigint");

                    b.Property<long>("idLocationDied")
                        .HasColumnType("bigint");

                    b.Property<long>("idLocationHome")
                        .HasColumnType("bigint");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("startus")
                        .HasColumnType("int");

                    b.HasKey("idClientDetail");

                    b.ToTable("ClientDeail");
                });

            modelBuilder.Entity("WebApiGP.Data.Family", b =>
                {
                    b.Property<long>("idFamily")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("bigIdFamily")
                        .HasColumnType("bigint");

                    b.Property<long>("idGiaPha")
                        .HasColumnType("bigint");

                    b.Property<long>("idLocationHome")
                        .HasColumnType("bigint");

                    b.HasKey("idFamily");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("WebApiGP.Data.IDGiaPha", b =>
                {
                    b.Property<long>("idGiaPha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idGiaPha");

                    b.ToTable("idGiaPha");
                });

            modelBuilder.Entity("WebApiGP.Data.LocationDieadDetail", b =>
                {
                    b.Property<long>("idLocationDiedDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("latiude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLocationDiedDetail");

                    b.ToTable("LocationDieadDetail");
                });

            modelBuilder.Entity("WebApiGP.Data.LocationDied", b =>
                {
                    b.Property<long>("idLocationDied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("idLocationDiedDetail")
                        .HasColumnType("bigint");

                    b.HasKey("idLocationDied");

                    b.ToTable("LocationDied");
                });

            modelBuilder.Entity("WebApiGP.Data.LocationHome", b =>
                {
                    b.Property<long>("idLocationHome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("latiude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLocationHome");

                    b.ToTable("LocationHome");
                });

            modelBuilder.Entity("WebApiGP.Data.ManagerIDGiaPha", b =>
                {
                    b.Property<long>("idManagerIDGiaPha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("idGiaPha")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idManagerIDGiaPha");

                    b.ToTable("ManagerIDGiaPha");
                });
#pragma warning restore 612, 618
        }
    }
}
